Repository Young-Child/FanFollow, pull requests merged in 2023-07, with the labels that each got.

#13 feat : Network 타입 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/NetworkManager/Network.swift
  FanFollow/FanFollow/Source/NetworkManager/NetworkError.swift
  FanFollow/FanFollow/Source/NetworkManager/NetworkManager.swift
  FanFollow/FanFollow/Source/ViewController.swift
Labels: feature

#14 config : Bundle Extension 구현 및 SupabaseInfo.plist 추가하여 Key값 보관
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/SupabaseInfo.plist
  FanFollow/FanFollow/Source/Util/Extension/Bundle+Extension.swift
Labels: config

#15 Like Service 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/LikeService.swift
  FanFollow/FanFollow/Source/Data/Model/LikeDTO.swift
  FanFollow/FanFollow/Source/Data/Protocol/Service.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/LikeRequestDirector.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/URLRequestBuilder.swift
  FanFollow/FanFollow/Source/NetworkManager/Model/APIError.swift
  FanFollow/FanFollow/Source/NetworkManager/Model/HTTPMethod.swift
  FanFollow/FanFollow/Source/NetworkManager/NetworkManager.swift
  FanFollow/FanFollow/Source/ViewController.swift
Labels: feature

#19 feat : PostService 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/DefaultLikeService.swift
  FanFollow/FanFollow/Source/Data/DefaultPostService.swift
  FanFollow/FanFollow/Source/Data/Model/PostDTO.swift
  FanFollow/FanFollow/Source/Data/Protocol/LikeService.swift
  FanFollow/FanFollow/Source/Data/Protocol/PostService.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/PostRequestDirector.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/URLRequestBuilder.swift
  FanFollow/FanFollow/Source/NetworkManager/Network.swift
  FanFollow/FanFollow/Source/NetworkManager/NetworkManager.swift
  FanFollow/FanFollow/Source/Util/Constant.swift
Labels: feature

#21 feat : FollowService 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/DefaultFollowService.swift
  FanFollow/FanFollow/Source/Data/Model/FollowDTO.swift
  FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift
  FanFollow/FanFollow/Source/Data/Protocol/FollowService.swift
  FanFollow/FanFollow/Source/Data/Protocol/Service.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/FollowRequestDirector.swift
  FanFollow/FanFollow/Source/Util/Extension/URL+Extension.swift
Labels: feature

#29 feat : LikeService 세부 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/DefaultLikeService.swift
  FanFollow/FanFollow/Source/Data/Model/LikeDTO.swift
  FanFollow/FanFollow/Source/Data/Protocol/LikeService.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/LikeRequestDirector.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/PostRequestDirector.swift
  FanFollow/FanFollow/Source/Util/Constants/SupabaseConstants.swift
Labels: feature

#31 [TEST] 네트워크 매니저 테스트 작성 test
  .github/workflows/BuildTest.yml
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow.xctestplan
  FanFollow/FanFollow/Source/NetworkManager/NetworkManager.swift
  FanFollow/FanFollow/Source/NetworkManager/Protocol/URLSessionDataTaskType.swift
  FanFollow/FanFollow/Source/NetworkManager/Protocol/URLSessionType.swift
  FanFollow/FanFollowTests/FanFollowTests.swift
  FanFollow/NetworkManagerTests/Mock/Mock.swift
  FanFollow/NetworkManagerTests/Mock/MockData.swift
  FanFollow/NetworkManagerTests/Mock/MockURLSessionDataTask.swift
  FanFollow/NetworkManagerTests/NetworkManagerTests.swift
  FanFollow/NetworkManagerTests/Stub/StubURLSession.swift
Labels: test

#30 feat : UserService 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/DefaultFollowService.swift
  FanFollow/FanFollow/Source/Data/DefaultUserInformationService.swift
  FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift
  FanFollow/FanFollow/Source/Data/Protocol/FollowService.swift
  FanFollow/FanFollow/Source/Data/Protocol/UserInformationService.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/FollowRequestDirector.swift
  FanFollow/FanFollow/Source/NetworkManager/Builder/UserRequestDirector.swift
Labels: feature

#34 [TEST] StubNetworkManager 타입 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/ServiceTests/Stub/StubNetworkManager.swift
Labels: test

#37 [TEST] Chat Service Test
  .github/workflows/BuildTest.yml
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow.xctestplan
  FanFollow/ServiceTests/ChatServiceTests.swift
  FanFollow/ServiceTests/Mock/Mock.swift
  FanFollow/ServiceTests/Stub/StubNetworkManager.swift
Labels: test

#36 [TEST] FollowService, UserInformationService 테스트 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/ServiceTests/FollowServiceTests.swift
  FanFollow/ServiceTests/UserInformationServiceTests.swift
Labels: test

#38 [TEST] PostService 테스트 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/DefaultPostService.swift
  FanFollow/FanFollow/Source/Data/Protocol/PostService.swift
  FanFollow/ServiceTests/Mock/Mock.swift
  FanFollow/ServiceTests/PostServiceTests.swift
Labels: test

#40 [Test] LikeService 테스트 코드 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/ServiceTests/LikeServiceTests.swift
  FanFollow/ServiceTests/Mock/Mock.swift
  FanFollow/ServiceTests/PostServiceTests.swift
  FanFollow/ServiceTests/UserInformationServiceTests.swift
Labels: test

#46 [REFACTOR] Clean Architecure 적용
  .github/workflows/BuildTest.yml
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Repository/DefaultChatRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultFollowRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultLikeRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultPostRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift
  FanFollow/FanFollow/Source/Data/Service/DefaultNetworkService.swift
  FanFollow/FanFollow/Source/Data/Service/NetworkService.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/ChatRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/FollowRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/LikeRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/PostRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/FanFollow/Source/Network/Builder/ChatRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Builder/FollowRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Builder/LikeRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Builder/PostRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Builder/URLRequestBuilder.swift
  FanFollow/FanFollow/Source/Network/Builder/UserRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Model/APIError.swift
  FanFollow/FanFollow/Source/Network/Model/HTTPMethod.swift
  FanFollow/FanFollow/Source/Network/NetworkError.swift
  FanFollow/FanFollow/Source/Network/Protocol/Service.swift
  FanFollow/FanFollow/Source/Network/Protocol/URLSessionDataTaskType.swift
  FanFollow/FanFollow/Source/Network/Protocol/URLSessionType.swift
  FanFollow/NetworkServiceTests/Mock/Mock.swift
  FanFollow/NetworkServiceTests/Mock/MockData.swift
  FanFollow/NetworkServiceTests/Mock/MockURLSessionDataTask.swift
  FanFollow/NetworkServiceTests/NetworkServiceTests.swift
  FanFollow/NetworkServiceTests/Stub/StubURLSession.swift
  FanFollow/RepositoryTests/ChatServiceTests.swift
  FanFollow/RepositoryTests/FollowServiceTests.swift
  FanFollow/RepositoryTests/LikeServiceTests.swift
  FanFollow/RepositoryTests/Mock/Mock.swift
  FanFollow/RepositoryTests/PostServiceTests.swift
  FanFollow/RepositoryTests/Stub/StubNetworkService.swift
  FanFollow/RepositoryTests/UserInformationServiceTests.swift
Labels: feature

#52 [FEATURE] AccessChatRoomUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Model/ChatDTO.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultChatRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/ChatRoom.swift
  FanFollow/FanFollow/Source/Domain/UseCase/AccessChatRoomUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/ChatRequestDirector.swift
  FanFollow/RepositoryTests/ChatServiceTests.swift
Labels: feature

#56 [FEATURE] User 타입 구현 및 관련 타입 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/Creator.swift
  FanFollow/FanFollow/Source/Domain/Model/Fan.swift
  FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift
  FanFollow/FanFollow/Source/Domain/Model/User.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/RepositoryTests/FollowServiceTests.swift
  FanFollow/RepositoryTests/UserInformationServiceTests.swift
Labels: feature

#53 [FEATURE] ChangeLikeUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/ChangeLikeUseCase.swift
Labels: feature

#50 [FEATURE] Main Scene UI 구성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Presenter/ExampleScene/View/ExampleViewController.swift
  FanFollow/FanFollow/Source/Presenter/MainScene/View/TabBarController.swift
Labels: UI

#59 [FEATURE] FetchUserInformationUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/Model/Creator.swift
  FanFollow/FanFollow/Source/Domain/Model/Fan.swift
  FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift
  FanFollow/FanFollow/Source/Domain/Model/User.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchUserInformationUseCase.swift
Labels: feature

#58 [FEATURE] FetchCreatorInformationUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorInformationUseCase.swift
Labels: feature

#57 [FEATURE] FetchCreatorPostsUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorPostsUseCase.swift
Labels: feature

#62 [FEATURE] 탭 내 Setting 과 관련된 View 생성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/ExampleProfile.imageset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/SecondaryColor.colorset/Contents.json
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/TopTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/SettingTabItem.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Protocol/Reusable.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Protocol/TabItem.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/TabBar.swift
  FanFollow/FanFollow/Source/Presenter/Comman/ViewModel/Protocol/ViewModel.swift
  FanFollow/FanFollow/Source/Presenter/MainScene/View/TabBarController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingBaseCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingSectionHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/ViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UITableView+Extension.swift
Labels: feature, UI

#61 [FEATURE] ExploreUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/UserRequestDirector.swift
Labels: feature

#65 [TEST] UseCase(FetchFeedUseCase 외) 테스트 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow.xctestplan
  FanFollow/UseCaseTests/ChangeLikeUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorPostsUseCaseTests.swift
  FanFollow/UseCaseTests/FetchFeedUseCaseTests.swift
  FanFollow/UseCaseTests/FetchUserInformationUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubLikeRepository.swift
  FanFollow/UseCaseTests/Stub/StubPostRepository.swift
  FanFollow/UseCaseTests/Stub/StubUserInformationRepository.swift
Labels: test

#69 [TEST] AccessChatRoomUseCase Test 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/UseCaseTests/AccessChatRoomUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubChatRepository.swift
Labels: test

#68 [FEATURE] Setting View Model 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/TopTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/SettingTabItem.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/TabBar.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/SettingViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UITableView+Extension.swift
Labels: feature, UI

#72 [TEST] ExploreUseCase Test
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift
  FanFollow/UseCaseTests/ExploreUseCaseTests.swift
Labels: test

#75 [FEATURE] SearchCreatorUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/AccessChatRoomUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/SearchCreatorUseCase.swift
Labels: feature

#76 [FEATURE] URL Request Builder 이미지 데이터 넣을 수 있도록 변경
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultImageRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/ImageRepository.swift
  FanFollow/FanFollow/Source/Network/Builder/ImageRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Builder/URLRequestBuilder.swift
  FanFollow/FanFollow/Source/Network/Model/HTTPBody.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/SettingViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
Labels: feature

#83 [FEATURE] ExploreView, ExploreViewModel 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Assets.xcassets/CategoryCellColor.colorset/Contents.json
  FanFollow/FanFollow/Source/Domain/Model/ExploreSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/ExploreSectionModel.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ExploreTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/ExploreTapItem.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Protocol/Reusable.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/View/CategoryCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/View/CreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/View/ExploreCollectionReusableHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ViewModel/ExploreViewModel.swift
  FanFollow/FanFollow/Source/Presenter/MainScene/View/TabBarController.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UICollectionView+Extension.swift
Labels: feature, UI

#86 [FEATURE] ExploreCategoryView, ViewModel 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/ExploreCollectionReusableHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/ViewModel/ExploreCategoryViewModel.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/CategoryCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/ViewModel/ExploreViewModel.swift
  FanFollow/UseCaseTests/ExploreUseCaseTests.swift
Labels: feature, UI

#85 [FEATURE] FeedViewModel, FeedViewController, PostCell 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Assets.xcassets/FeedTopAppImage.imageset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/FeedTopAppImage.imageset/FeedTopAppImage.png
  FanFollow/FanFollow/Source/Data/Model/ChatDTO.swift
  FanFollow/FanFollow/Source/Data/Model/FollowDTO.swift
  FanFollow/FanFollow/Source/Data/Model/PostDTO.swift
  FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultChatRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultFollowRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultPostRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/Post.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/PostRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/FeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/ViewModel/FeedViewModel.swift
  FanFollow/FanFollow/Source/Presenter/MainScene/View/TabBarController.swift
  FanFollow/FanFollow/Source/Util/Extension/Date+Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/JSONDecoder+Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
  FanFollow/NetworkServiceTests/NetworkServiceTests.swift
  FanFollow/RepositoryTests/ChatRepositoryTests.swift
  FanFollow/RepositoryTests/FollowRepositoryTests.swift
  FanFollow/RepositoryTests/LikeRepositoryTests.swift
  FanFollow/RepositoryTests/PostRepositoryTests.swift
  FanFollow/RepositoryTests/UserInformationRepositoryTests.swift
  FanFollow/UseCaseTests/ExploreUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorPostsUseCaseTests.swift
  FanFollow/UseCaseTests/FetchFeedUseCaseTests.swift
  FanFollow/UseCaseTests/FetchUserInformationUseCaseTests.swift
  FanFollow/UseCaseTests/SearchCreatorUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubPostRepository.swift
  FanFollow/UseCaseTests/Stub/StubUserInformationRepository.swift
Labels: feature, UI

#89 [FEATURE] FeedManageViewModel, FeedManageViewController 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/Model/CreatorInformationSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/FeedManageSectionModel.swift
  FanFollow/FanFollow/Source/Domain/Model/Post.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorInformationUseCase.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/CreatorInformationCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/FeedManageViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/ViewModel/FeedManageViewModel.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/ViewModel/FeedViewModel.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubFollowRepository.swift
Labels: feature, UI, test

#91 [FEATURE] FeedCoordinator 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Coordinator/AppCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/Coordinator.swift
  FanFollow/FanFollow/Source/Coordinator/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/MainTabBarCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Domain/UseCase/ExampleUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/TopTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/ExampleScene/ViewModel/ExampleViewModel.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/FeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/SettingViewController.swift
Labels: feature, UI

#94 [FEATURE] ExploreCoordinator 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/ExploreCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/MainTabBarCoordinator.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ExploreTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift
Labels: feature

#97 [FEATURE] Profile Setting View Controller
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Info.plist
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Data/Model/UserInformationDTO.swift
  FanFollow/FanFollow/Source/Domain/Model/Creator.swift
  FanFollow/FanFollow/Source/Domain/Model/Fan.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Domain/Model/User.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchUserInformationUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UpdateProfileImageUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UpdateUserInformationUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/PhotoAssetGridViewController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Protocol/Reusable.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/AssetImageGridCell.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/JobCategoryPickerView.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/ProfileInputControls/ProfileInput.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/ProfileInputControls/ProfileInputTextField.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/ProfileInputControls/ProfileInputTextView.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/ProfileInputControls/ProfileLinkInputField.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/UnderLineTextField.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorListCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/CreatorInformationCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileSettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/SettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/ProfileImagePickerViewModel.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/ProfileSettingViewModel.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/SettingViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/Notification + Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UICollectionView + Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UILabel+Extension.swift
Labels: feature, UI

#101 [FEATURE]/ExploreSubscribeView, ViewModel 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorInformationUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/ExploreTapItem.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/ViewModel/ExploreSubscribeViewModel.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
Labels: feature, UI

#99 [FEATURE] Setting 화면에 대한 Coordinator 설정
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Application/SceneDelegate.swift
  FanFollow/FanFollow/Source/Coordinator/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/ProfileImagePickerCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/ProfileSettingCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileSettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/SettingViewController.swift
  FanFollow/FanFollow/Source/Util/Extension/Bundle+Extension.swift
Labels: feature, UI

#102 [BUG] Image 설정 메서드 변경으로 인한 버그 수정
  FanFollow/FanFollow/Source/Coordinator/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Domain/Model/Post.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UpdateProfileImageUseCase.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorListCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/CreatorInformationCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileSettingViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ProfileThumbnailCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/ProfileSettingViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
Labels: bug

#104 [FEATURE] ProfileFeedViewModel,ProfileFeedViewController 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Domain/Model/ProfileFeedSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/ProfileFeedSectionModel.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorInformationUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/SettingTabItem.swift
  FanFollow/FanFollow/Source/Presenter/FeedManageScene/View/CreatorInformationCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/FeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileCell.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileFeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/ViewModel/ProfileFeedViewModel.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
Labels: feature, UI, test

#105 [FEATURE] ExploreView 내부에서 ProfileFeedView로 이동 구현
  FanFollow/FanFollow/Source/Coordinator/ExploreCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ExploreTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/ViewModel/ExploreViewModel.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift
Labels: feature, UI
