Repository Young-Child/FanFollow, pull requests merged in 2023-08, with the labels that each got.

#108 Post Cell 기획 및 디자인 변경으로 인한 수정
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  FanFollow/FanFollow/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/팬팔아이콘.png
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/팬팔아이콘@2x.png
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/팬팔아이콘@3x.png
  FanFollow/FanFollow/Source/Coordinator/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultImageRepository.swift
  FanFollow/FanFollow/Source/Data/Service/LinkCacheService.swift
  FanFollow/FanFollow/Source/Domain/Model/ExampleModel.swift
  FanFollow/FanFollow/Source/Domain/Model/Post.swift
  FanFollow/FanFollow/Source/Domain/Model/PostSectionModel.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/ImageRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchFeedUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/ImageRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/HorizontalImageSlideView.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/LinkPreview.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/FeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCreatorHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/ViewModel/FeedViewModel.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileCell.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileFeedViewController.swift
Labels: feature, UI

#111 Explore 탭 뷰 세부 설정
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/appIcon.png
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/appIcon@2x.png
  FanFollow/FanFollow/Resource/Assets.xcassets/iconImage.imageset/appIcon@3x.png
  FanFollow/FanFollow/Source/Coordinator/ExploreCoordinator.swift
  FanFollow/FanFollow/Source/Domain/Model/ExploreSectionItem.swift
  FanFollow/FanFollow/Source/Domain/UseCase/ExploreUseCase.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/CreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/Common/ExploreCollectionReusableHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/View/ExploreCategoryViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreCategoryScene/ViewModel/ExploreCategoryViewModel.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/CategoryCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/View/ExploreViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreMainScene/ViewModel/ExploreViewModel.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSearchScene/View/ExploreSearchViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeScene/View/ExploreSubscribeViewController.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileFeedViewController.swift
  FanFollow/UseCaseTests/ExploreUseCaseTests.swift
Labels: UI

#110 [FEATURE] 크리에이터 신청 화면 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/SettingScene/CreatorApplicationCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Domain/Model/CreatorApplicationStep.swift
  FanFollow/FanFollow/Source/Domain/UseCase/ApplyCreatorUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/JobCategoryPickerView.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileFeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorApplicationPageViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorApplicationViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorIntroduceViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorJobCategoryPickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorLinksTableViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ButtonCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationStepView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationTextFieldCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationTextFieldView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/PlaceholderTextView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/CreatorApplicationViewModel.swift
  FanFollow/UseCaseTests/ApplyCreatorUseCaseTests.swift
Labels: feature, UI, test

#114 [FEATURE] Upload 기능 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/UploadCoordinator.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultPostRepository.swift
  FanFollow/FanFollow/Source/Domain/Model/Upload.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UpdateProfileImageUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UploadPostUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/ImageRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/ImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/BottomSheetScene/UploadBottomSheetView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/BottomSheetScene/UploadBottomSheetViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/LinkUploadScene/UploadLinkPreView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/LinkUploadScene/UploadLinkViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/PhotoUploadScene/UploadImageCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/PhotoUploadScene/UploadImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/PhotoUploadScene/UploadPhotoViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewModel/UploadViewModel.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/ProfileImagePickerViewController.swift
  FanFollow/FanFollow/Source/Util/Constants/SupabaseConstants.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIButton+Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UIImageView + Extension.swift
  FanFollow/FanFollow/Source/Util/Extension/UI/UITextField+Extension.swift
Labels: feature, UI

#113 Feature/setting coordinators
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Resource/Info.plist
  FanFollow/FanFollow/Source/Coordinator/Coordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/BugReportCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/EvaluateAppCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/OpenSourceCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/SettingViewController.swift
  FanFollow/Settings.bundle/Root.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
  FanFollow/Settings.bundle/com.mono0926.LicensePlist.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist/Kingfisher.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist/RxDataSources.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist/RxSwift.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist/SnapKit.plist
  FanFollow/Settings.bundle/com.mono0926.LicensePlist/Then.plist
  FanFollow/Settings.bundle/en.lproj/Root.strings
Labels: UI, config

#116 [TEST] UploadPostUseCase
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UploadPostUseCase.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/LinkUploadScene/UploadLinkViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/PhotoUploadScene/UploadPhotoViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewModel/UploadViewModel.swift
  FanFollow/UseCaseTests/ExploreUseCaseTests.swift
  FanFollow/UseCaseTests/SearchCreatorUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubImageRepository.swift
  FanFollow/UseCaseTests/UploadPostUseCaseTest.swift
Labels: bug, test

#119 [FEATURE] AuthRepository 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Model/Provider.swift
  FanFollow/FanFollow/Source/Data/Model/SessionDTO.swift
  FanFollow/FanFollow/Source/Data/Model/SessionError.swift
  FanFollow/FanFollow/Source/Data/Model/StoredSession.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultAuthRepository.swift
  FanFollow/FanFollow/Source/Data/Service/UserDefaultsService.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/AuthRepository.swift
  FanFollow/FanFollow/Source/Network/Builder/AuthRequestDirector.swift
  FanFollow/RepositoryTests/AuthRepositoryTests.swift
  FanFollow/RepositoryTests/Stub/StubUserDefaultsService.swift
Labels: feature, test

#122 Upload 관련 UI 디테일 반영 및 버그 수정
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/ExploreScene/ExploreCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/FeedScene/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/UploadCoordinator.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultFollowRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultImageRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/ImageRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/FetchCreatorPostsUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UploadPostUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/ImageRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Controller/SettingTabBarController.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/Model/SettingTabItem.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/LinkPreview.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/UnderLineTextField.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/LinkUploadScene/UploadLinkPreView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/UploadBottomSheetView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/UploadContentTextView.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/UploadImageCell.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/View/UploadLinkPreview.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadBottomSheetViewController/UploadBottomSheetViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadImagePickerViewController/UploadImagePickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadViewController/UploadLinkViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadViewController/UploadPhotoViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewController/UploadViewController/UploadViewController.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/UploadScene/ViewModel/UploadViewModel.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/FeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCell.swift
  FanFollow/FanFollow/Source/Presenter/FeedScene/View/PostCreatorHeaderView.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileCell.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/View/ProfileFeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/ProfileFeedScene/ViewModel/ProfileFeedViewModel.swift
  FanFollow/FanFollow/Source/Util/Extension/Array + Extension.swift
  FanFollow/UseCaseTests/FetchCreatorPostsUseCaseTests.swift
  FanFollow/UseCaseTests/FetchUserInformationUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubImageRepository.swift
  FanFollow/UseCaseTests/UploadPostUseCaseTest.swift
Labels: bug, UI

#125 [FEATURE] Creator 신청 화면 UI 구성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/SettingScene/CreatorApplicationCoordinator.swift
  FanFollow/FanFollow/Source/Domain/Model/CreatorApplicationStep.swift
  FanFollow/FanFollow/Source/Domain/Model/JobCategory.swift
  FanFollow/FanFollow/Source/Domain/UseCase/UpdateUserInformationUseCase.swift
  FanFollow/FanFollow/Source/Presenter/Comman/UI/View/JobCategoryPickerView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/ChildCreatorApplicationControllers/CreatorApplicationChildController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/ChildCreatorApplicationControllers/CreatorIntroduceViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/ChildCreatorApplicationControllers/CreatorJobCategoryPickerViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/ChildCreatorApplicationControllers/CreatorLinksTableViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorApplicationPageViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorApplicationViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/Controller/CreatorApplication/CreatorLinksTableViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/ButtonCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationLinkCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationStepView.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/View/CreatorApplicationTextFieldCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ViewModel/CreatorApplicationViewModel.swift
Labels: feature, UI

#128 [FEATURE] AppleLogIn 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/FanFollow.entitlements
  FanFollow/FanFollow/Resource/Assets.xcassets/Apple.imageset/Contents.json
  FanFollow/FanFollow/Resource/Assets.xcassets/Apple.imageset/Frame 170.png
  FanFollow/FanFollow/Resource/Assets.xcassets/mainLogo.imageset/6.png
  FanFollow/FanFollow/Resource/Assets.xcassets/mainLogo.imageset/62x.png
  FanFollow/FanFollow/Resource/Assets.xcassets/mainLogo.imageset/63x.png
  FanFollow/FanFollow/Resource/Assets.xcassets/mainLogo.imageset/Contents.json
  FanFollow/FanFollow/Source/Coordinator/AppCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/LogInScene/LogInCoordinator.swift
  FanFollow/FanFollow/Source/Data/Model/SessionError.swift
  FanFollow/FanFollow/Source/Data/Model/StoredSession.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultAuthRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/LogInScene/AppleSigningUseCase.swift
  FanFollow/FanFollow/Source/Network/Builder/AuthRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/LogInScene/View/LogInViewController.swift
  FanFollow/FanFollow/Source/Presenter/LogInScene/ViewModel/LogInViewModel.swift
  FanFollow/RepositoryTests/AuthRepositoryTests.swift
Labels: feature, UI

#127 [FEATURE] SignUpUserUseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Repository/DefaultUserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/SignUpUserUseCase.swift
  FanFollow/RepositoryTests/UserInformationRepositoryTests.swift
  FanFollow/UseCaseTests/SignUpUserUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubUserInformationRepository.swift
Labels: feature, test

#130 [TEST] AppleSigningUseCase Test Code 작성
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/UseCaseTests/AppleSigningUseCaseTests.swift
  FanFollow/UseCaseTests/Stub/StubAuthRepository.swift
Labels: test

#135 [FEATURE] 사용자 신고 기능
  FanFollow/FanFollow/Source/Coordinator/ExploreScene/ProfileFeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/FeedScene/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/MailCoordinator.swift
  FanFollow/FanFollow/Source/Presenter/Common/UI/View/NavigationBar.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/Controllers/ProfileFeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/ViewModel/ProfileFeedViewModel.swift
  FanFollow/FanFollow/Source/Util/Constants/Constants.swift
Labels: feature, UI

#136 [FEATURE] Creator agreement(이용 약관) View 추가
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Domain/Model/Setting/CreatorApplicationStep.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/CreatorApplicationView/Controllers/ChildControllers/CreatorAgreementViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/CreatorApplicationView/Controllers/CreatorApplicationViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/CreatorApplicationView/View/CreatorApplicationStepView.swift
  FanFollow/FanFollow/Source/Util/Constants/Constants.swift
Labels: feature, UI

#137 [FEATURE] App privacy 안내 사항 로그인에 추가
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/LogInScene/LogInCoordinator.swift
  FanFollow/FanFollow/Source/Data/Service/DefaultNetworkService.swift
  FanFollow/FanFollow/Source/Domain/Model/Setting/CreatorApplicationStep.swift
  FanFollow/FanFollow/Source/Network/Directors/UserRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/Common/UI/View/LinkableLabel.swift
  FanFollow/FanFollow/Source/Presenter/LogInScene/Controllers/LogInViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/CreatorApplicationView/Controllers/ChildControllers/CreatorAgreementViewController.swift
  FanFollow/FanFollow/Source/Util/Constants/Constants.swift
Labels: feature

#142 [FEATURE] Content Block 기능 관련 Director, Repository, UseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Repository/DefaultBlockContentRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/BlockContentRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/Post/BlockContentUseCase.swift
  FanFollow/FanFollow/Source/Network/Directors/BlockContentRequestDirector.swift
Labels: feature

#141 [FEATURE] 신고 관련 Director, Repository, UseCase 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Data/Repository/DefaultAuthRepository.swift
  FanFollow/FanFollow/Source/Data/Repository/DefaultReportRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/AuthRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/FollowRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/LikeRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/PostRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/ReportRepository.swift
  FanFollow/FanFollow/Source/Domain/RepositoryInterface/UserInformationRepository.swift
  FanFollow/FanFollow/Source/Domain/UseCase/Auth/SignUpUserUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/Post/FetchFeedUseCase.swift
  FanFollow/FanFollow/Source/Domain/UseCase/User/SendReportUseCase.swift
  FanFollow/FanFollow/Source/Network/Directors/LikeRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Directors/PostRequestDirector.swift
  FanFollow/FanFollow/Source/Network/Directors/ReportRequestDirector.swift
  FanFollow/FanFollow/Source/Presenter/ExploreScene/ExploreSubscribeView/ViewModel/ExploreSubscribeViewModel.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/Controllers/UploadLinkViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/Controllers/UploadPhotoViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/UploadPostView/View/UploadImageCell.swift
  FanFollow/FanFollow/Source/Util/Extension/Notification + Extension.swift
  FanFollow/RepositoryTests/AuthRepositoryTests.swift
  FanFollow/RepositoryTests/FollowRepositoryTests.swift
  FanFollow/RepositoryTests/Stub/StubNetworkService.swift
  FanFollow/UseCaseTests/ApplyCreatorUseCaseTests.swift
  FanFollow/UseCaseTests/ChangeLikeUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorInformationUseCaseTests.swift
  FanFollow/UseCaseTests/FetchCreatorPostsUseCaseTests.swift
  FanFollow/UseCaseTests/FetchFeedUseCaseTests.swift
  FanFollow/UseCaseTests/FetchUserInformationUseCaseTests.swift
  FanFollow/UseCaseTests/SignUpUserUseCaseTests.swift
Labels: feature

#148 [FEATURE] 차단 사용자 관리 화면 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SettingCoodinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/BlockCreatorManagementCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/CreatorApplicationCoordinator.swift
  FanFollow/FanFollow/Source/Domain/Model/Setting/BlockCreator.swift
  FanFollow/FanFollow/Source/Domain/Model/Setting/BlockCreatorSectionModel.swift
  FanFollow/FanFollow/Source/Domain/Model/Setting/SettingSectionItem.swift
  FanFollow/FanFollow/Source/Domain/Model/Setting/SettingSectionModel.swift
  FanFollow/FanFollow/Source/Domain/UseCase/User/ManageBlockCreatorUseCase.swift
  FanFollow/FanFollow/Source/Network/Directors/BlockUserDirector.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/Controllers/BlockCreatorManagementViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/View/BlockCreatorCell.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/BlockCreatorManagementView/ViewModel/BlockCreatorManagementViewModel.swift
  FanFollow/FanFollow/Source/Util/Constants/Constants.swift
Labels: feature, UI

#149 [FEATURE] 유저 차단 기능 구현
  FanFollow/FanFollow.xcodeproj/project.pbxproj
  FanFollow/FanFollow/Source/Coordinator/Coordinator.swift
  FanFollow/FanFollow/Source/Coordinator/ExploreScene/ProfileFeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/FeedScene/FeedCoordinator.swift
  FanFollow/FanFollow/Source/Coordinator/SettingScene/SubCoordinators/WithdrawalCoordinator.swift
  FanFollow/FanFollow/Source/Presenter/Common/UI/Controller/BottomSheetViewController.swift
  FanFollow/FanFollow/Source/Presenter/LogInScene/Provider.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/Controllers/BlockUserViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/Controllers/ProfileFeedViewController.swift
  FanFollow/FanFollow/Source/Presenter/SettingScene/ProfileFeedView/ViewModel/BlockUserViewModel.swift
  FanFollow/FanFollow/Source/Util/Constants/Constants.swift
Labels: feature, UI
